priv/templates/enum.ex.eex
priv/templates/message.ex.eex
priv/templates/service.ex.eex

Modules generated by protoc are not documented but still appear in ex_doc documentation. Defaulting to `@moduledoc false` hides the generated modules from ex_doc. I think in most cases messages/enums/services will be internal implementation details to the projects using them and won't be documented. Docs can still be added after generating the modules but this seems like a better default.

Set @moduledoc false on generated modules

---

lib/protobuf/validator.ex
test/protobuf/validator_test.exs
test/support/test_msg.ex

```elixir
defmodule Oneof do
use Protobuf, syntax: :proto3
defstruct [:option]
oneof :option, 0
field :option_a, 1, optional: true, type: :string, oneof: 0
field :option_b, 2, optional: true, type: :int32, oneof: 0
end
```
```elixir
> Oneof.new(option: {:option_a, "string"}) |> Oneof.encode()
** (Protobuf.InvalidError) Oneof#option_a is invalid!
```
Oneof fields are not present in generated struct and Map.get/1 in validator returns nil which is not allowed value for scalar types in proto3

Fix scalar types in oneof for proto3

---

lib/protobuf/decoder.ex
lib/protobuf/encoder.ex
lib/protobuf/wire_types.ex

As we discussed/discovered the other day, we can use `defmacro` to define these constant and use them just fine in binary-pattern-matching.
Added `()` after macro call for clear marking, actual not sure whether it will work without `()`...

Use macro to centralize wire types declaration

---

lib/google/protobuf/timestamp.pb.ex
lib/google/protobuf/timestamp.proto

Add `Google.Protobuf.Timestamp` type. This allows protobuf file that contain `google.protobuf.Timestamp` type be able to use a generated code without any error.
Google Protobuf file for Timestamp type is also added as a reference for this new type.
Please note that, in proto3 version, variable will be marked as optional by default.

Add Google Protobuf Timestamp type

---

test/protobuf/issue_test.exs

```
1) test oneof proto3 (Protobuf.IssueTest)
test/protobuf/issue_test.exs:8
Assertion with == failed
code:  assert msg == msg |> Encoder.encode() |> Decoder.decode(TestMsg.OneofProto3)
left:  %TestMsg.OneofProto3{other: "other", first: {:b, ""}, second: {:c, 0}}
right: %TestMsg.OneofProto3{other: "other", first: nil, second: nil}
stacktrace:
test/protobuf/issue_test.exs:10: (test)
```

Add a failing oneof test case

---

.travis.yml

Exclude 1.4 and 1.5 w/ OTP 21.0 since TravisCI doesn't support this (Hex does
not supply such combination yet?)

Add OTP 21.0 to build matrix, also try building a package

---

lib/protobuf/protoc/generator/message.ex
test/protobuf/protoc/generator/message_test.exs

Messages without fields still need typespecs, especially if those messages types are referenced from other message types.

Generate typespecs for messages with no fields

---

lib/protobuf/dsl.ex
lib/protobuf/encoder.ex
test/protobuf/encoder_test.exs
test/support/test_msg.ex

When an enum is included as part of a oneof, encoding and `__default_struct__` do not work properly.
Encode breaks with a raise, and `__default_struct__` includes a value for the enum.

Fix oneof enum encoding

---

README.md
lib/google/descriptor.pb.ex
lib/protobuf/protoc/cli.ex
lib/protobuf/protoc/context.ex
lib/protobuf/protoc/generator/enum.ex
lib/protobuf/protoc/generator/message.ex
lib/protobuf/protoc/generator/service.ex
lib/protobuf/protoc/template.ex
priv/templates/enum.ex.eex
priv/templates/message.ex.eex
priv/templates/service.ex.eex
test/protobuf/protoc/cli_test.exs
test/protobuf/protoc/generator/enum_test.exs
test/protobuf/protoc/generator/message_test.exs
test/protobuf/protoc/generator/service_test.exs
test/protobuf/protoc/proto_gen/test.pb.ex

There is a great deal of information in the descriptors that unfortunately is lost with the current approach.
Most protubuf libraries provide access to the raw descriptors, this PR brings this lib inline with that philosophy by
adding the encoded descriptor to the generated modules and exposing them via a `descriptor` function.

Add descriptors to generated protos

---

README.md
lib/protobuf/dsl.ex
lib/protobuf/field_props.ex
test/protobuf/dsl_test.exs
test/support/test_msg.ex

Spent some time digging for the `deprecated` field option, realized it existed but was just excluded from the field options struct. Adding it here because we already have that data, and it's useful to be able to know programmatically if a field is deprecated.
Also updated the README with instructions on how to get the test suite running.

Add deprecated to field props

---

lib/protobuf/dsl.ex

In this code we're building the default struct for Proto2 at compile time, and then building off from that struct to make the proto3 struct **at runtime**. There's no need to do that at runtime as far as I can tell, we can just do that at compile time too. That makes `MyProtoSchema.new()` about 3.5x faster from my benchmarks.
cc @tony612

Improve performance of __default_struct__/0

---

lib/protobuf/encoder.ex
test/protobuf/encoder_test.exs
test/support/test_msg.ex

This MR fixes the encoder when it is encoding required enums in proto2 by not skipping them when they are the "default" value.
A specific example that I have ran into that was causing issues is encoding `CommandAck` from the Pulsar protobuf [spec](https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/proto/PulsarApi.proto). 
```protobuf
message CommandAck {
enum AckType {
Individual = 0;
Cumulative = 1;
}
required uint64 consumer_id       = 1;
required AckType ack_type         = 2;
...
}
```
```elixir
%Proto.CommandAck{
ack_type: 0,
consumer_id: 1,
...
}
```
`ack_type` is a required enum. This library was skipping encoding due to it being the default value which causes the pulsar server to close the connection and log an exception saying the message was missing fields. …

Encode required enums for proto2

---

lib/protobuf/protoc/generator/enum.ex
lib/protobuf/protoc/generator/message.ex
lib/protobuf/protoc/template.ex
lib/protobuf/type_util.ex
priv/templates/enum.ex.eex
test/protobuf/protoc/generator/enum_test.exs
test/protobuf/protoc/generator/message_test.exs

The protoc plugin generates structs for `message`s together with their types. It doesn't however do that for `enum`s and it could be very helpful to generate types for enums too, so that they can be reffered to in other areas of the code.
Let me know what you think :)

Generate enum types

---

lib/protobuf.ex
lib/protobuf/builder.ex
test/protobuf/builder_test.exs

cc @keathley as mentioned in #76 and cc @tony612 for review 🙃

Raise on non-existing fields in Protobuf.Builder.new/2

---

lib/protobuf/dsl.ex
test/protobuf/dsl_test.exs
test/support/test_msg.ex

Protobuf enums can define aliases when the `allow_alias` option is set. This is common to both proto2 and proto3.
https://developers.google.com/protocol-buffers/docs/proto#enum
https://developers.google.com/protocol-buffers/docs/proto3#enumerations

Add enum alias support

---

lib/protobuf/dsl.ex
lib/protobuf/json.ex
lib/protobuf/json/decode.ex
lib/protobuf/json/decode_error.ex
test/protobuf/dsl_test.exs
test/protobuf/json/decode_test.exs
test/protobuf/json/encode_test.exs
test/protobuf/json_test.exs
test/support/doctest.ex
test/support/test_msg.ex

Addresses the second part of #86. Follow-up to #105.
This feature allows us to decode messages from JSON in addition to protobuf binaries.
It follows Google's specs and reference implementation. Only `proto3` syntax is supported at the moment and some features, such as well-known types, are not fully supported yet.
JSON decoding relies on the `Jason` library. Support to other JSON engines may be added in the future.
https://developers.google.com/protocol-buffers/docs/proto3#json
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf
Huge thanks again to @whatyouhide and @amiel for their support and effort put into this.
This implementation iterates over the fields metadata to read from the JSON input. This means unknown fields will always be ignored and also means …

New feature: JSON decoding

---

lib/protobuf/protoc/generator/message.ex

Make sure it renders correctly when the list of extensions is long.

Fix extensions generator output

---

bench/script/bench.exs
lib/protobuf/decoder.ex
lib/protobuf/wire_types.ex
test/protobuf/decoder_test.exs

Groups are a deprecated feature only available in proto2. However, most of Google's benchmarks datasets still use it. 
This change adds partial support to that feature, by skipping group data. Now, when an incoming payload contains a group the decoder no longer crashes – it will skip ahead until the group is over and keep reading the remaining fields normally. So, this can be helpful for projects that receive old proto2 messages over the wire too.
Parsing groups is an important step torwards conformance to the specs, but it comes at the cost of a few extra logical branches when decoding field keys and values. Part of this problem can be mitigated in the future if we eventually decide to separate some proto3 logic from the proto2 core – since proto3 is more strict, we can make more …

Accept groups on decoding

---

bench/script/bench.exs
bench/script/load.exs

Separating part of #118 into its own PR to make local testing easier for everyone.
* Increase run time for more accuracy
* Enable memory measurements
* Bring back `google_message3_1`, even though it may go over the established run time
* Select the longest payload rather than the first one
* Output comparison to console in addition to HTML

Tweak benchmark scripts

---

lib/protobuf/encoder.ex
test/pbt/encode_decode_type_test.exs
test/pbt/encode_decode_varint_test.exs
test/protobuf/encoder/encode_type_test.exs
test/protobuf/encoder/encode_varint_test.exs

Reducing the amount of intermediate binaries allocated speeds up encoding and potentially decreases memory usage.
I'm usually very distrustful of local benchmarks, so it'd be very reassuring to see some production numbers with these optimizations applied. Anyway, these are the results I've got running against `master`:
```
Name                                                ips        average  deviation         median         99th %
encode (optimized)                              24.24 K       41.26 μs  ±4792.01%           0 μs           0 μs
encode (master)                                 10.70 K       93.47 μs  ±2984.15%          12 μs          32 μs
Comparison: 
encode (optimized)                              24.24 K
encode (master)                                 10.70 K - 2.27x …
```

Leverage iodata on encoding

---

lib/protobuf/decoder.ex

Benchmark results:
```
Name                                              ips        average  deviation         median         99th %
decode (optimize-packed-99926e5-decode)       61.33 K       16.31 μs   ±963.31%           8 μs          30 μs
decode (master-3428d3a-decode)                51.89 K       19.27 μs   ±883.01%           9 μs          37 μs
Comparison: 
decode (optimize-packed-99926e5-decode)       61.33 K
decode (master-3428d3a-decode)                51.89 K - 6.59x slower +16.35 μs
Memory usage statistics:
Name                                       Memory usage
decode (optimize-packed-99926e5-decode)         6.84 KB
decode (master-3428d3a-decode)                  8.48 KB - 9.44x memory usage +7.59 KB
Name                                              ips        average …
```

Optimize decoding of keys and packed fields

---

bench/.gitignore
bench/README.md
bench/script/standard_bench.exs

Protobuf includes benchmarks for its official language implementations, such as Python, C++ and Golang. They measure average encode and decode throughput for each built-in dataset. This is useful to check how Elixir matches up with them.
https://github.com/protocolbuffers/protobuf/blob/master/benchmarks/README.md
For each dataset, it runs decode (then encode) on all the payloads. If that dry run takes longer than 3s, its time is taken as the average. Otherwise, repeat a few runs and average their times.
Throughput is measured in MB/s, always based on the binary payload size from the dataset, even when the output size doesn't match – which is the case when the messages include proto2 groups, which are currently skipped. This can give unreliable results, so it's important to take that into …

Add protobuf standard benchmarks

---

lib/protobuf/protoc/generator/message.ex
lib/protobuf/type_util.ex
test/protobuf/protoc/generator/message_test.exs

Removing `[]` out of `Protobuf.Protoc.Generator.Message.fmt_type/1` and
add `[]` into `Protobuf.TypeUtil.enum_to_spec/3` when `TYPE_MESSAGE` is match
alongs with repeated true.
Fixes #132

Fix repeated enum field generate [[]] into typespec

---

lib/protobuf/wire/varint.ex

That warning no longer shows up in Elixir 1.12, but still does in 1.11 and lower. Adding `generated: true` in a few places fixes it.
warning: the result of the expression is ignored (suppress the warning by assigning the expression to the _ variable)
lib/protobuf/decoder.ex:103

Fix compiler warning for Elixir versions prior to 1.12

---

lib/application.ex
lib/protobuf/dsl.ex
lib/protobuf/extension.ex

Opportunistic refactoring from the work on #164. Concentrated config-reading code inside `get_all_modules`, optimized `cal_extensions` to do fewer iterations and removed a few unreachable/redundant code paths.

Refactor some extensions-related code

---

bench/lib/benchmarks.pb.ex
bench/lib/datasets/google_message1/proto2/benchmark_message1_proto2.pb.ex
bench/lib/datasets/google_message1/proto3/benchmark_message1_proto3.pb.ex
bench/lib/datasets/google_message2/benchmark_message2.pb.ex
bench/lib/datasets/google_message3/benchmark_message3.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_1.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_2.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_3.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_4.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_5.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_6.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_7.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_8.pb.ex
bench/lib/datasets/google_message4/benchmark_message4.pb.ex
bench/lib/datasets/google_message4/benchmark_message4_1.pb.ex
bench/lib/datasets/google_message4/benchmark_message4_2.pb.ex
bench/lib/datasets/google_message4/benchmark_message4_3.pb.ex
lib/elixirpb.pb.ex
lib/google/compiler/plugin.pb.ex
lib/google/descriptor.pb.ex
lib/protobuf/builder.ex
lib/protobuf/protoc/generator/message.ex
mix.exs
priv/templates/message.ex.eex
test/protobuf/protoc/generator/message_test.exs
test/protobuf/protoc/proto_gen/extension.pb.ex
test/protobuf/protoc/proto_gen/test.pb.ex

Closing https://github.com/elixir-protobuf/protobuf/pull/184 again in favor of this, which I think has a stronger overall approach. This is only step number 1 and not everything is working, but as far as I can tell, nothing is _broken_. We might generate `nil` in some places where we could be more precise, but I don't think we're generating anything wrong in any place.

Type-aware struct defaults, again

---

bench/lib/benchmarks.pb.ex
bench/lib/datasets/google_message1/proto2/benchmark_message1_proto2.pb.ex
bench/lib/datasets/google_message1/proto3/benchmark_message1_proto3.pb.ex
bench/lib/datasets/google_message2/benchmark_message2.pb.ex
bench/lib/datasets/google_message3/benchmark_message3.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_1.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_2.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_3.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_4.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_5.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_6.pb.ex
bench/lib/datasets/google_message3/benchmark_message3_7.pb.ex
bench/lib/datasets/google_message4/benchmark_message4.pb.ex
bench/lib/datasets/google_message4/benchmark_message4_1.pb.ex
bench/lib/datasets/google_message4/benchmark_message4_2.pb.ex
lib/elixirpb.pb.ex
lib/google/compiler/plugin.pb.ex
lib/google/descriptor.pb.ex
priv/templates/message.ex.eex
test/protobuf/protoc/generator/message_test.exs
test/protobuf/protoc/proto_gen/extension.pb.ex
test/protobuf/protoc/proto_gen/test.pb.ex

There is a default function implementation included in `use Protobuf` so there is no need to generate it.

Do not generate overridable transformer_module/0

---

lib/protobuf/encoder.ex
test/protobuf/decoder_test.exs
test/protobuf/encoder_test.exs

Previously, when encoding values that are default values (`skip_field?() => true`) the transformer module was not triggered so we now delay the `skip_field?` check until we have called the transformer module.

Fix encoding default value when using transformer module

---

.github/workflows/conformance.yml
conformance/exemptions.txt
lib/protobuf/json/decode.ex
test/protobuf/json/decode_test.exs

* We now check that floats are in the valid float range when decoding JSON
* We now support "casting" of floats in JSON into integers if the type of the field in the schema is an integer

Improve parsing of floats in JSON

---

conformance/exemptions.txt
lib/protobuf/json/decode.ex
lib/protobuf/json/encode.ex
lib/protobuf/json/encode_error.ex
lib/protobuf/json/rfc3339.ex
lib/protobuf/json/utils.ex
test/protobuf/json/decode_test.exs
test/protobuf/json/encode_test.exs
test/protobuf/json/utils_test.exs

I also added some unit tests for encoding and decoding `Google.Protobuf.Duration`. Nice!

Fix conformance tests for Google.Protobuf.Duration

---

bench/script/bench.exs
conformance/protobuf/runner.ex
lib/protobuf.ex
lib/protobuf/encoder.ex
lib/protobuf/protoc/cli.ex
test/pbt/encode_decode_type_test.exs
test/protobuf/encoder_test.exs
test/protobuf/encoder_validation_test.exs
test/protobuf/protobuf_test.exs

These two new functions support options. Options were already supported
by `Protobuf.Encoder.encode/2`, but they were not public API.
For now, the only supported option is `:iolist`.
Closes #221.

Add Protobuf.encode/2 and c:Protobuf.encode/2

---

lib/protobuf/dsl.ex
lib/protobuf/wire.ex
test/protobuf/decoder_test.exs
test/protobuf/dsl_test.exs
test/protobuf/wire_test.exs

Right now, the library warns if we decode an enum for which we don't know the **atom value**. That is, if you have an enum like this:
```protobuf
enum Status {
LOGGED_IN = 0;
LOGGED_OUT = 1;
}
```
and you decode it with a version of the schemas that don't have the `LOGGED_OUT = 1` definition, then the library is going to return `1` as the enum value. This is the correct thing to do to ensure backwards and forwards compatibility.
However, warning for this case is problematic. In many cases, applications want to handle these unknown enums *by design* and do their own thing or ignore the warning. Additionally, this is a 100% functional library so adding a "stateful" component (the logging) feels inappropriate.
When decoding enums, your business logic should always plan for unknown enums …

Don't log warning when decoding unknown enums

---

lib/protobuf/encoder.ex
test/protobuf/encoder_test.exs
test/support/test_msg.ex

Don't skip storing the value of a oneof field even if it's the default value

---

lib/protobuf/decoder.ex
test/protobuf/decoder_test.exs

Previously when an unknown wire_type was encountered a `CaseClauseError`
exception would be raised. This commit updates the decoder so that a
`Protobuf.DecodeError` with a slightly helpful error message is raised.

Update Decoder - handle unknown wire_type

---

lib/protobuf/wire/varint.ex

Compilation fails with 1.9.4 using the `--warnings-as-errors` with the
warning that "the result of the expression is ignored". This commit
simply assigns the result to `_` to suppress the warning.
Note: This warning doesn't appear in your CI but it does show on [this page](https://github.com/elixir-protobuf/protobuf/commit/fe11c65da7f8316faa01c4f4336557a8708b7a6e#diff-572680e4c3bdfcb24caac848aefec9c3065cdaa9d43c60d9dd343eb57d2cc4dd). It blocked our fork, hence the fix, but maybe you've already worked around it somehow?

Fix compilation warning for Elixir 1.9.4

---

lib/protobuf/decoder.ex
test/protobuf/decoder_test.exs

Previously when decoding a delimited field, if the given binary has insufficient
data a `MatchError` was raised when attempting to pattern match on the
next value in the field. This commit updates the code to check the
length before attempting the match, and throws a `Protobuf.DecodeError`
with a more informative message.
Note: If you prefer not use the throw/catch we can refactor

Update Decoder: handle MatchError when decoding

---

test/protobuf/dsl/typespecs_test.exs
test/protobuf/protoc/generator/message_test.exs

By calling `Macro.to_string/1` on both sides of the assertion the tests will pass regardless if different Elixir versions format differently.

Fix failing tests due to formatting

---

lib/protobuf/dsl/typespecs.ex
test/protobuf/dsl/typespecs_test.exs
test/protobuf/protoc/generator/message_test.exs

Oneofs are optional so they can be unset.

Add nil to oneof typespec union

---

lib/protobuf/encoder.ex
test/protobuf/encoder_test.exs
test/support/test_msg.ex

Right now, `Protobuf.Encoder.encode/1` only attempts to invoke a custom `TransformModule` behaviour for nested structs in its recursive encoding iterations. If the struct passed into `encode/1` itself has a custom transformer, it is ignored.
This PR ensures that `encode/1` calls a custom transformer on the struct passed into the function, as well as its nested children. The approach I took mimics existing logic in `Protobuf.Decoder.decode/2` ([ref](https://github.com/elixir-protobuf/protobuf/blob/b84b9978c7e7007166d2b7ad7feb7b1ca780e556/lib/protobuf/decoder.ex#L20)).

fix(encoding): Ensure transform_module is called for struct passed into `Protobuf.Encoder.encode/2`

---

lib/protobuf/protoc/generator.ex

Consider this proto file:
// helloworld.proto
syntax = "proto3";
package helloworld;
// The greeting service definition.
service Greeter {
// Sends a greeting
rpc SayHello (HelloRequest) returns (HelloReply) {}
rpc CheckHeaders (HeaderRequest) returns (HeaderReply) {}
}
// The request message containing the user's name.
message HelloRequest {
string name = 1;
}
// The response message containing the greetings
message HelloReply {
string message = 1;
}
message HeaderRequest {
}
message HeaderReply {
string authorization = 1;
}
When running with current release protoc-gen-elixir (0.10.0). Code will
output as:
defmodule Helloworld.HelloRequest do
@moduledoc false
use Protobuf, protoc_gen_elixir_version: "0.10.0", syntax: :proto3
field :name, 1, type: :string
end
defmodule …

Improve code format generator

---

mix.exs

When building protoc-gen-elixir plugin, we don't want to include
test/dev dependencies (stream_data, etc)

Force prod env for escript.build task

---

lib/protobuf/builder.ex

Related issue: https://github.com/elixir-protobuf/protobuf/issues/287
The previous typespecs weren't allowing types like:
```
@spec not_fine :: Timestamp.t()
def not_fine do
Timestamp.new(seconds: 232_342, nanos: 232_342)
end
```
Because the `Builder.new` typespecs were requiring a map with only the `:__struct__` key.

Add optional keys to Builder typespecs

---

.github/workflows/latest_conformance.yml
mix.exs

The issue here was that we are compiling from `.proto` files in the `deps/google_protobuf` directory, which is fixed to v3.17 of Protobuf right now (for reproducibility). However, the "latest conformance" CI job uses the latest `main` from Protobuf for the conformance tests, but not for the `.proto` source files. This means that some tests were failing because they expected the latest `.proto` source files.
This PR introduces `PROTOBUF_ROOT` so that we can use the conformance runner and `.proto` files from the same directory.

Enable PROTOBUF_ROOT env variable

---

lib/protobuf/encoder.ex
test/protobuf/encoder_validation_test.exs

When using `oneof`'s in client stubs, an user can specify a non-existing field. 
For example:
Imagine we have this proto :
```proto
message LoginRequest {
reserved 420, 69;
string username = 1;
oneof credential {
string password = 2;
string googleOauthCode = 3;
string magicLinkToken = 4;
}
}
```
And the user writes this code : 
```elixir
req = Service.LoginRequest.new(username: "foo", credential: {:undefined_credential, "stuff"}) #oops
```
If he tries to encode this message, he'll be met with an unfriendly error message : `(MatchError) no match of right hand side value: nil`.
This PR implements a more friendly error message in these cases.

Add nicer oneof error messages

---

lib/protobuf/encoder.ex
test/protobuf/decoder_test.exs
test/protobuf/encoder_test.exs
test/support/test_msg.ex

Currently with proto3 optional values, a zero/default value is skipped. This means that `decode(encode(msg))` is not identity for all messages with proto3 optional fields.
This PR ensures that only nil values for proto3_optional fields are skipped.

Fix decoding of proto3 optional zero/default values

---

lib/protobuf/dsl/typespecs.ex
test/protobuf/dsl/typespecs_test.exs

Hey folks! 🖖 
Typespecs for fields with `proto3_optional` flag are missing `nil` as a possible value. This pull request fixes the issue by including `nil` as a possible typespec value when a field has the `proto3_optional` flag enabled. 
Closes #312.
Consider the proto3 message with an optional field: 
```proto
syntax = "proto3";
// ...
message Person {
optional int32 identifier = 1;
}
```
Currently, the following type is generated for the above message:
```elixir
@type t :: %Person{
identifier: integer(), # <-- note it is missing `| nil`, as `identifier` is optional 
__unknown_fields__: [...]
}
```
After this pull request, typespecs for `optional` fields in proto3 will include `nil` as a possible value:
```elixir
@type t :: %Person{ 
identifier: integer() | nil, 
__unknown_fields__: …
```

Fixes typespecs for proto3_optional fields

---

.github/workflows/latest_conformance.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

Stop using deprecated ::set-output from GH Actions

---

lib/protobuf/protoc/generator/message.ex
mix.exs
test/protobuf/protoc/generator_integration_test.exs
test/protobuf/protoc/proto/no_package.proto

In `nested_maps/2`, the fully qualified name was built without discarding the nil entries of the list. This meant that map fields worked correctly for .proto files that contained a package, but failed to do so in .proto files that did not, since the map key had then an extra `.` in front that made the lookup in `get_field/4` fail.
This also adds a test case (that was failing with the old version and is now succeeding) to avoid regressions.
Fix #321
Signed-off-by: Riccardo Binetti <rbino@gmx.com>

Fix map fields contained in .proto files without a package

---

.formatter.exs
lib/elixirpb.pb.ex
lib/google/protobuf/compiler/plugin.pb.ex
lib/google/protobuf/descriptor.pb.ex
lib/protobuf/any.ex
lib/protobuf/protoc/generator/enum.ex
lib/protobuf/protoc/generator/message.ex
priv/templates/enum.ex.eex
priv/templates/message.ex.eex
priv/templates/service.ex.eex
test/protobuf/any_test.exs

The idea here is to push people to use `Google.Protobuf.Any` directly more. The default `type_url` can be written down manually, and it's probably going to be a lot more accurate.
I'm thinking of removing `Protobuf.Any.type_url_to_module/1` too and make it a private function in this library instead of part of the public API. Thoughts @ericmj?

Remove pack/1 and unpack/2 from Protobuf.Any

---

lib/elixirpb.pb.ex
lib/elixirpb/pb_extension.pb.ex
lib/google/protobuf/descriptor.pb.ex
lib/protobuf.ex
lib/protobuf/dsl.ex
lib/protobuf/extension.ex
lib/protobuf/message_props.ex
lib/protobuf/protoc/cli.ex
lib/protobuf/protoc/context.ex
lib/protobuf/protoc/generator.ex
lib/protobuf/protoc/generator/extension.ex
lib/protobuf/protoc/generator/message.ex
priv/templates/extension.ex.eex
priv/templates/message.ex.eex
test/protobuf/extension_test.exs
test/protobuf/protobuf_test.exs
test/protobuf/protoc/cli_integration_test.exs
test/protobuf/protoc/generator/extension_test.exs
test/protobuf/protoc/generator_test.exs
test/protobuf/protoc/proto/test.proto

Closes #88.
The idea here is:
* Generate one extension module per message, as suggested by @ericmj (https://github.com/elixir-protobuf/protobuf/issues/88#issuecomment-961293983)
* For extensions defined at the `.proto` file level, we generate a unique module name like `<package>.Extensions<unique_int>.PbExtension`. The `<unique_int>` part is calculated by using `erlang:phash2/1` on the sorted list of extensions definitions in the file. That way it stays mostly the same when regenerating, module reordering them too.

Fix multiple conflicting PbExtension modules

---

lib/protobuf.ex

Old docs in `Protobuf` module (and hex docs) don't work with a 0.10.0 change not requiring `defstruct` when making a new protobuf module.
Before change:
After change:
Because of this change, the example from the Protobuf behaviour hex docs can be used without edits.

Update docs to work with v0.10.0

---

lib/protobuf/json/decode.ex
test/protobuf/json/decode_test.exs
test/protobuf/json/encode_test.exs

Add support for handling "." in FieldMask paths when JSON decoding

---

lib/protobuf.ex

Should update the a hex docs section to show a code snippet as code instead of just text.
Old text:

Correctly indent code block in docs

---

lib/protobuf.ex

Same issue as in https://github.com/elixir-protobuf/protobuf/issues/287, the typespec was over constrained and not really accepting the structs as it should

Add optional keys to `Protobuf.decode/2` typespecs

---

README.md

The repository was moved to `elixir-grpc/grpc`

Fixed link to the gRPC Elixir implementation

---

mix.exs

This fixes the issue that `option (elixirpb.file).module_prefix` is not loaded correctly if the protobuf package is installed from Hex, due to missing lib/elixirpb/pb_extension.pb.ex in the 0.11.0 or 0.12.0 packages.
Closes #367

Add lib/elixirpb to package files

---

lib/protobuf/json/encode.ex
test/protobuf/json/decode_test.exs
test/protobuf/json/encode_test.exs

It fixes the same issue but now for the JSON encoder like https://github.com/elixir-protobuf/protobuf/pull/302
Currently with proto3 optional values, a zero/default value is skipped. This means that the JSON `decode(encode(msg))` is not the same for all messages with proto3 optional fields.
This PR ensures that attributes containing the default values are not skipped for proto3_optional fields.

Fix JSON encoding of proto3 optional non-nil defaults

---

lib/protobuf/encoder.ex
test/protobuf/encoder_test.exs
test/protobuf/message_merge_test.exs
test/support/test_msg.ex

Closes https://github.com/elixir-protobuf/protobuf/issues/365
This is a breaking change, as you could rely on the automatic transformation between structs. I don't think that should be done, though.

Don't encode a struct as another struct

---

lib/protobuf.ex
lib/protobuf/dsl/typespecs.ex
lib/protobuf/field_props.ex
lib/protobuf/wire.ex
lib/protobuf/wire/types.ex
test/protobuf/dsl/typespecs_test.exs
test/protobuf/protoc/generator/message_test.exs

This type is referenced from the typespecs generated by the protoc extension. When building documentation for the protobufs (that is, using include_docs=true), it can't be resolved and ex_doc will print the following warning for every struct:
warning: documentation references type "Protobuf.Wire.Types.wire_type()" but it is hidden or private.
By making it public, the warning is resolved, and it becomes clickable on hexdocs.
Another alternative to solve the issue (while keeping the internal type private) would be to change the typespec of `:__unknown_fields__` to avoid referring to it, instead referring to a public type.

Move wire_type() to Protobuf, create Protobuf.unknown_fields() type

---

lib/protobuf/transform_module.ex

Noticed while opening #382.
Per 0.13.0, calling `defstruct` (without `@type`) raises a compile error (see https://github.com/elixir-protobuf/protobuf/blob/0f5e070961bd06f53572bcc0fd55fe8d0d478f03/test/protobuf/dsl_test.exs#L280)

Fix broken code example in Protobuf.TransformModule docs

---

lib/protobuf/json/decode.ex
test/protobuf/json/decode_test.exs

JSON has a single type for numbers. The same number can be written as `42` or `42.0`. Without additional context, this number should be valid in any of the Protobuf numeric types. For reference, the `protobuf` Python library is totally fine decoding `{ "foo": 42 }` with either a `float` or an `int32` Protobuf field.

Decode integer-formatted JSON numbers as float (#364)

---

lib/protobuf.ex
lib/protobuf/dsl.ex
lib/protobuf/transform_module.ex
lib/protobuf/transform_module/infer_fields_from_enum.ex
test/protobuf/protoc/cli_integration_test.exs
test/support/test_msg.ex

Adds a `typespec/1` macrocallback to transform module behaviour.
This macro can modify the typespec for modules using it. This way, we can provide correct typespecs for modules using transformers. A "breaking" change is that transform modules can't depend on Protobuf definitions anymore. This is quite easily solvable, though.
Closes #382 
--------------------------------------------------
**Previous description, from previous implementation:**
We detect that `transform_module/0` was defined through a on_definition hook. We then store the module in an attribute. This attribute is later used by the `before_compile` callback to set the typespec, which is set in the form of:
```elixir
@type t() :: transform_module.t(__MODULE__)
```
Then, transform modules can implement proper typespecs.
No …

Add `typespec/1` macro to transform module behaviour

---

conformance/exemptions.txt
lib/protobuf/json/encode.ex
lib/protobuf/protoc/generator/message.ex
test/protobuf/protoc/generator/message_test.exs

Fixes >500 conformance tests
- Makes proto2 also support json_name. This alone fixes >200 tests
- Ensures JSON encoder decides correctly when to emit or not emit fields (at the very least, more correctly than before :))

Support json_name for proto2; Ensures proper field emission for JSON encoder

---

lib/protobuf/encoder.ex
test/protobuf/encoder_test.exs

Because of the recursive implementation of `encode_fields`, unrelated
fields would get mixed up in encode errors.
For example, our struct `%TestMsg.Foo` has fields `:a`, `:b`, `:c`,
`:d`, `e` (and more...). If we had an error at `:e`, we would get the
error popping up for all fields coming before it:
```elixir
iex(1)>  %TestMsg.Foo{a: 90, e: %TestMsg.Foo.Bar{a: "not_a_number"}} |> Protobuf.encode()
** (Protobuf.EncodeError) Got error when encoding TestMsg.Foo#a: ** (Protobuf.EncodeError) Got error when encoding TestMsg.Foo#b: ** (Protobuf.EncodeError) Got error when encoding TestMsg.Foo#c: ** (Protobuf.EncodeError) Got error when encoding TestMsg.Foo#d: ** (Protobuf.EncodeError) Got error when encoding TestMsg.Foo#e: ** (Protobuf.EncodeError) Got error when encoding TestMsg.Foo.Bar#a: ** …
```

Fix mangled Protobuf.EncodeError 

---

lib/protobuf/decoder.ex
lib/protobuf/json.ex
test/protobuf/conformance_regressions_test.exs

Different from the previous fixes in #390, I'm not 100% sure about this one. Feels like it could/should be solved in a different layer, but I didn't find a better way to do it without breaking anything else.

Fix decoding of maps to match conformance tests

---

lib/protobuf/protoc/generator/util.ex
test/protobuf/protoc/generator_test.exs

We must manually add it, as `Code.format_string!` doesn't add a newline to end of file, nor does protoc.
Closes #380

Ensure there's a newline in the end of generated files

---

.github/workflows/main.yml
lib/protobuf/json.ex
lib/protobuf/json/decode_error.ex
lib/protobuf/json/json_library.ex
test/protobuf/builder_test.exs
test/protobuf/encoder_test.exs
test/protobuf/json_test.exs

This implementation defaults to `JSON` if it's available. If it's not,
it tries to use `Jason` as it did before.
Some exceptions are changed (only for `JSON`, `Jason` is unaffected). For
example, instead of `Jason.DecodeError`, when using `JSON` we raise
`Protobuf.JSON.DecodeError`, and encode errors have a more varied shape
(since they can be mostly anything coming from Elixir side).
Additionally, it adds 1.18.1 in CI. Once it's working in both versions, I'll 
remove 1.17.x.

Add native Elixir `JSON` support

---

lib/protobuf/encoder.ex

Only encode/1 was applying transform in the outer struct

Fix encode_to_iodata/1 not matching encode/1 behaviour

---

lib/elixirpb.pb.ex
lib/elixirpb/pb_extension.pb.ex
lib/google/protobuf/any.pb.ex
lib/google/protobuf/compiler/plugin.pb.ex
lib/google/protobuf/descriptor.pb.ex
lib/google/protobuf/duration.pb.ex
lib/google/protobuf/empty.pb.ex
lib/google/protobuf/field_mask.pb.ex
lib/google/protobuf/struct.pb.ex
lib/google/protobuf/timestamp.pb.ex
lib/google/protobuf/wrappers.pb.ex
mix.exs

This is done to avoid breaking apps that depended on google_protos descriptor functionality that needs to update to the latest `protobuf` version.
solves: https://github.com/elixir-protobuf/protobuf/issues/401

Google_protos with descriptor 

---

README.md

Ive spent a good amount of time figuring out why our protobufs didnt compile anymore. 
It turned out that the version being installed in the CI was `0.14` and not `0.11` as in the application. 
I added a warning for this to the readme, because I feel it could save other people a lot of time.
Perhaps for the Google machine, the error I got was the following:
```== Compilation error in file  lib/protobuf/indexer_service.pb.ex ==
** (KeyError) key :features not found
(protobuf 0.11.0) expanding struct: Google.Protobuf.MethodOptions.__struct__/1
lib/protobuf/indexer_service.pb.ex:13: IndexerService.Service.descriptor/0```

Update readme to warn against using different escript and deps versions.

---

lib/protobuf/encoder.ex
lib/protobuf/json/encode.ex
lib/protobuf/presence.ex
lib/protobuf/text.ex
test/protobuf/presence_test.exs
test/protobuf/text_test.exs
test/support/test_msg.ex

This PR is on-top of #398.
Adds a unified presence tracking module. Makes the different encoders use it when deciding whether to skip a field or not.
Adds a public API for checking field presence on `Protobuf.Presence.field_presence/2`. This is similar to the feature present on the official protobuf libraries, but with a different API.
In Ruby, for example, fields that have **explicit presence tracking** generate a `has_{field_name}?` method:
```ruby
message = MyMessage.new()
message.has_foo? #=> false
message.foo = 0
message.has_foo? # => true
```
If another field, say `bar`, doesn't have explicit presence tracking (e.g.: it is a non-optional, non-one_of proto3), it simply doesn't generate the `has_bar?` method, so you can't "presence-check" these fields.
My proposed API is a bit …

Create Protobuf.Presence module

---

.github/workflows/latest_conformance.yml
.github/workflows/main.yml

Extracted from #405 
CI was not running due to deprecated Ubuntu image and cache action.

Fix ci: update actions and ubuntu image

---

lib/protobuf/dsl/typespecs.ex

Instead of raising, holds the file compilation until the module is available.
Solves compilation issue when using `one_file_per_module=true` and map types, where it would raise due to `Code.ensure_loaded?` returning false for a module that wasn't compiled yet.

Use `ensure_compiled!` instead of `ensure_loaded?` on map typespec macro

---

lib/google/protobuf.ex

Can't use `duration.second` because you may have minutes, weeks, etc to consider.

Fix formula for converting Duration into google.protobuf.Duration
