elixir-protobuf/protobuf

lib/protobuf/protoc/generator/message.ex, lib/protobuf/type_util.ex, test/protobuf/protoc/generator/message_test.exs
=> Add nil as possible type for nested message

Makefile, lib/google/descriptor.pb.ex, src/elixir.proto
=> update elixir_module_prefix to field num allocated by google

lib/protobuf/encoder.ex, test/protobuf/encoder_test.exs
=> Fixed proto3 lost oneof values

lib/protobuf/dsl.ex, lib/protobuf/encoder.ex
Also, consider run `mix format` at some point?
=> Remove several unused warnings

.travis.yml, lib/protobuf/decoder.ex, lib/protobuf/encoder.ex, lib/protobuf/error.ex, test/protobuf/encoder/encode_type_test.exs, test/protobuf/encoder_validation_test.exs
=> fix(encode): validate int range

lib/protobuf/dsl.ex, lib/protobuf/protoc/generator.ex, lib/protobuf/protoc/generator/message.ex, test/protobuf/protoc/generator/message_test.exs
Fixes https://github.com/tony612/protobuf-elixir/issues/74
=> Fix gen order

lib/protobuf/decoder.ex, test/protobuf/decoder_test.exs
=> Raise DecodeError if the binary cannot be parsed

lib/protobuf/protoc/frame/metadata.ex, lib/protobuf/protoc/frame/parser.ex
The changes are in two files:
- /frame/metadata: implemented needed functions for `protoc-gen-validate`, not all functions
- /frame/parser.ex: implemented parsing nested messages
=> Add nested messages parse.

.travis.yml, bench/lib/benchmarks.pb.ex, bench/lib/datasets/google_message1/benchmark_message1_proto2.pb.ex, bench/lib/datasets/google_message1/benchmark_message1_proto3.pb.ex, lib/google/compiler/plugin.pb.ex, lib/google/descriptor.pb.ex
* Update the CI matrix
* Bump Elixir and Erlang
* ~Drop Elixir 1.7 and Erlang 20.0 support~
* Bump Protobuf and recompile internal protos
=> Update Elixir, Erlang and Protobuf

test/protobuf/protoc/generator/enum_test.exs, test/protobuf/protoc/generator/message_test.exs
=> Fix test brokens

README.md, lib/protobuf/protoc/cli.ex, lib/protobuf/protoc/context.ex, lib/protobuf/protoc/generator.ex, lib/protobuf/protoc/generator/enum.ex, lib/protobuf/protoc/generator/extension.ex, lib/protobuf/protoc/generator/message.ex, lib/protobuf/protoc/generator/service.ex, test/protobuf/protoc/cli_test.exs, test/protobuf/protoc/generator/enum_test.exs, test/protobuf/protoc/generator/extension_test.exs, test/protobuf/protoc/generator/message_test.exs, test/protobuf/protoc/generator/service_test.exs, test/protobuf/protoc/generator_test.exs
Closes https://github.com/elixir-protobuf/protobuf/issues/153.
Paired with @ericmj.
=> Add one_file_per_module CLI option

.github/workflows/main.yml, .gitignore, mix.exs, test/protobuf/protoc/cli_integration_test.exs, test/protobuf/protoc/generator_integration_test.exs
At least we regularly test `protoc-gen-elixir` 😉
=> Add some CLI integration tests

mix.exs, test/protobuf/protobuf_test.exs, test/protobuf/protoc/generator_integration_test.exs, test/protobuf/protoc/proto/custom_options.proto
=> Add failing tests for custom options

conformance/exemptions.txt, lib/protobuf/wire.ex, test/protobuf/conformance_regressions_test.exs, test/protobuf/wire_test.exs
Closes #224.
21 more conformance tests down 🔥
=> Cast sint* types correctly when they overflow

conformance/exemptions.txt, lib/protobuf/decoder.ex, test/protobuf/conformance_regressions_test.exs
=> Deep merge nested messages

lib/protobuf.ex, lib/protobuf/decoder.ex, lib/protobuf/dsl.ex, lib/protobuf/dsl/typespecs.ex, lib/protobuf/encoder.ex, lib/protobuf/message_props.ex, lib/protobuf/wire.ex, test/pbt/unknown_fields_test.exs, test/protobuf/decoder_test.exs, test/protobuf/dsl/typespecs_test.exs, test/protobuf/encoder_test.exs, test/protobuf/protobuf_test.exs, test/protobuf/protoc/generator/message_test.exs
As per @britto's comment: https://github.com/elixir-protobuf/protobuf/pull/233#issuecomment-992618149
=> Decode all unknown fields, not just varints

conformance/runner.sh, mix.exs
=> Use a shell script instead of a different escript for conformance tests

lib/protobuf/json.ex, lib/protobuf/json/decode.ex, lib/protobuf/json/encode.ex, lib/protobuf/json/utils.ex, test/protobuf/json_test.exs
=> Support JSON mapping in proto2

lib/protobuf/protoc/generator/util.ex, test/protobuf/protoc/generator/util_test.exs
Fixes https://github.com/elixir-protobuf/protobuf/issues/250
=> Fix generation of message module with lowercase name

lib/protobuf/protoc/cli.ex, lib/protobuf/protoc/generator/message.ex, lib/protobuf/protoc/generator/util.ex, test/protobuf/protoc/cli_integration_test.exs, test/protobuf/protoc/generator/enum_test.exs, test/protobuf/protoc/generator/util_test.exs
=> Camelize name components in generated types

lib/protobuf/protoc/cli.ex, test/protobuf/protoc/cli_integration_test.exs, test/protobuf/protoc/cli_test.exs
=> Ignore package_prefix for files we don't directly generated

mix.exs
=> Suffix version with `-dev` when not released

lib/protobuf/protoc/generator/enum.ex, lib/protobuf/protoc/generator/extension.ex, lib/protobuf/protoc/generator/message.ex, lib/protobuf/protoc/generator/service.ex, lib/protobuf/protoc/generator/util.ex, priv/templates/service.ex.eex, test/protobuf/protoc/generator/enum_test.exs, test/protobuf/protoc/generator/message_test.exs, test/protobuf/protoc/generator/service_test.exs
=> Include protoc-gen-elixir plugin version in generated files

.github/workflows/main.yml, bench/lib/benchmarks.pb.ex, bench/lib/datasets/google_message1/proto2/benchmark_message1_proto2.pb.ex, bench/lib/datasets/google_message1/proto3/benchmark_message1_proto3.pb.ex, bench/lib/datasets/google_message2/benchmark_message2.pb.ex, bench/lib/datasets/google_message3/benchmark_message3.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_1.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_2.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_3.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_4.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_5.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_6.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_7.pb.ex, bench/lib/datasets/google_message3/benchmark_message3_8.pb.ex, bench/lib/datasets/google_message4/benchmark_message4.pb.ex, bench/lib/datasets/google_message4/benchmark_message4_1.pb.ex, bench/lib/datasets/google_message4/benchmark_message4_2.pb.ex, bench/lib/datasets/google_message4/benchmark_message4_3.pb.ex, lib/elixirpb.pb.ex, lib/google/protobuf/compiler/plugin.pb.ex, lib/google/protobuf/descriptor.pb.ex
I couldn't improve the CI message much, but I capitalised it so maybe people like me will hopefully notice it better.
=> Update generated files and improve CI message

README.md
Related to: #297  
Update example of generated code and mix.exs dependencies to reflect latest version (0.10.0)
=> Update readme to 0.10.0

README.md, lib/elixirpb.pb.ex, lib/google/protobuf/compiler/plugin.pb.ex, lib/google/protobuf/descriptor.pb.ex, lib/protobuf/protoc/cli.ex, lib/protobuf/protoc/context.ex, lib/protobuf/protoc/generator/enum.ex, lib/protobuf/protoc/generator/message.ex, lib/protobuf/protoc/generator/service.ex, mix.exs, priv/templates/enum.ex.eex, priv/templates/message.ex.eex, priv/templates/service.ex.eex, test/protobuf/json/encode_test.exs, test/protobuf/protoc/cli_integration_test.exs, test/protobuf/protoc/cli_test.exs, test/protobuf/protoc/generator/enum_test.exs, test/protobuf/protoc/generator/message_test.exs, test/protobuf/protoc/generator/service_test.exs, test/test_helper.exs
Hey folks! 👋 
This pull request implements an initial version of the `include_docs` option, which was discussed in this https://github.com/elixir-protobuf/protobuf/issues/266#issuecomment-1059990482 issue.
=> Add include_docs option

.github/workflows/latest_conformance.yml, .github/workflows/main.yml, mix.exs, test/protobuf/conformance_regressions_test.exs, test/protobuf/dsl/typespecs_test.exs, test/protobuf/json/decode_test.exs
**Do not merge until 1.14 is released and it's added to the CI matrix!**
=> Fixes for Elixir 1.14

lib/protobuf/json/encode.ex, lib/protobuf/json/encode_error.ex, test/protobuf/json/encode_test.exs, test/protobuf/protoc/generator_integration_test.exs, test/protobuf/protoc/proto/test.proto
=> Fix JSON encoding map validation

conformance/protobuf/runner.ex
=> Run conformance tests on OTP >= 25
